### ISSUE TITLE
Segmentation fault when erasing

### ISSUE THREAD

**Issue by giomba** [GLGPrograms/uber-retro-programmer#2]
I have an Atmel AT28C64B EEPROM (15PU 1207), that I'm unable to write to.

I used the programmer software and firmware at version 7c92435c2f5812b7aff422483bae5f28cdccc069
I did:
```
$ ./serprog --unlock --write snake6502.bin --size 8192 --addr 0
[INFO   ] Successfully connected programmer URProgrammer
[INFO   ] Write errors: 0
[INFO   ] Unlocking memory...
[INFO   ] Write errors: 4298
[INFO   ] Beginning read
[ERROR  ] Failed verification
```

I thought that it could be due to a faulty memory, but I've programmed it some time ago with another programmer (codename djordjo). I'll re-try when possible.
So I just tried to erase the memory (even if this programmer just does it in software) and I did:
```
$ ./serprog --unlock --erase --size 8192
[INFO   ] Successfully connected programmer URProgrammer
[INFO   ] Write errors: 0
[INFO   ] Erasing device...
[INFO   ] Write errors: 7066
[INFO   ] Blank checking...
[INFO   ] Beginning read
[1]    220699 segmentation fault (core dumped)  ./serprog --unlock --erase --size 8192
```

And here you can see a segmentation fault of the host program.
Even if my EEPROM does not work, I think this shouldn't happen.

**Comment by giuliof** [comment]
Erase issue is solved in commit 158950462189b7a2bb912df1de3d5986e7c9e638.

Commit f42949c84fdb2a88d1de7f822309ec173e9908bc solves some issues with slower ROMs (and fixes a datasheet misunderstanding). But this is another issue...
